#%RAML 1.0 Trait

headers:
  clientId: 
    description: |
      The Id of requesting party. Set to optional for backward compatibility.
    type: string
    required: false
  clientSecret: 
    description: |
      The associated secret for the provided Id. Set to optional for backward compatibility.
    type: string
    required: false
  Authorization: 
    description: |
      (Deprecated) Authorization header for backward compatibility,.
    type: string
    required: false