#%RAML 1.0 DataType
type: object
properties:
  notification:
    type: object
    properties:
      notificationCenterId:
        required: false
        type: number
      individualId:
        type: string
        pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$
      notificationEventId:
        required: true
        type: number
      notificationMessage:
        required: true
        type: string
        maxLength: 1000
      notificationDataTags:
        required: true
        type: string
        maxLength: 500
      notificationTranslationTags:
        required: true
        type: string
        maxLength: 500
      noticationReadInd:
        required: true
        type: boolean
      insertedBy:
        required: true
        type: string
        maxLength: 100