mobile-sapi:
  https:
    host: "0.0.0.0"
    port: "8082"
  keystore:
    path: "security/keystore/keystore.jks"
  autodiscovery: ""
  basepath: "/api/sys/*"

isos-mssql:
  deviceinfo:
    host: "172.26.172.213"
    port: "1433"
    dbname: "MobileMiddleware"
 
